/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"




int main(void)
{

	#if (__FPU_PRESENT == 1) && (__FPU_USED == 1)

		SCB->CPACR |= ((3UL << (10*2)) | (3UL << (11*2)));

	#endif

    /* Loop forever */
	while(1){



	}
}
